config/routes.rb
Rails.application.routes.draw do
  resources :cars do 
    member do
      put :visible
    end
  end
  # Reportes
  resources :reports
  patch '/reports/:id/reject', to: 'reports#reject', as: '/reject/report'
  patch '/reports/:id/accept', to: 'reports#accept', as: '/accept/report'
  
  ##get '/reports/:id/create_report_message', to: 'reports#create_report_message', as: '/create_report_message/report'
  

  resources :cars_usage_histories,only: [:show], path: '/history', path_names: { show: '/' }
  # Existe una jerarquia top-down

  # Se quiere organizar grupos de controllers bajo un namespace
  # El directorio de ellos se encuentra en app/controllers/authentication
  # Ver CAP 2.6 guides.rubyonrails.org/routing.html
  # No se quiere que el namespace figure en la ruta, entonces se pasa vacio al path
  # Sino figuraria cómo /authentication/users/new 
  namespace :authentication, path: "", as: "" do
    # Super usuarios
    resources :super_users, only: [:index, :new, :create, :edit, :update, :show]
    patch '/super_users/:id/block', to: 'super_users#block', as: '/block/supervisor'
    delete '/super_users/:id/delete', to: 'super_users#destroy', as: '/delete/supervisor'

    # Usuarios
    resources :users, only: [:edit, :update]
    resources :users, only: [:new, :create], path: '/register', path_names: { new: '/' }
    get '/users', to: 'users#index', as: '/clients'
    get '/pre_registered', to: 'users#pre_registered', as: '/pre_registered'
    patch '/users/:id/block', to: 'users#block', as: '/block/client'
    delete '/users/:id/delete', to: 'users#destroy', as: '/delete/client'
    patch '/users/:id/accept', to: 'users#accept', as: '/accept/client'
    delete '/users/:id/reject', to: 'users#reject', as: '/reject/client'
    get '/users/:id/edit_password', to: 'users#edit_password', as: '/edit_password/user'
    patch '/users/:id/edit_password', to: 'users#update_password', as: '/update_password/user'
    get '/users/:id/edit_license', to: 'users#edit_license', as: '/edit_license/user'
    patch '/users/:id/edit_license', to: 'users#update_license', as: '/update_license/user'
    patch '/users/:id/accept_license', to: 'users#accept_license', as: '/accept_license/user'
    patch '/users/:id/reject_license', to: 'users#reject_license', as: '/reject_license/user'
    get '/users/:id/reject_message', to: 'users#reject_message', as: '/reject_message/client'
    get '/users/:id/show', to: 'users#show', as: '/show/client'
    
    # Sesiones
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
  end

  resources :main, only: [:index]
  

  #ruteo de la wallet management
  namespace :wallet_management, path: "", as:"" do
    resources :wallets, only: [:show] 
    put 'wallets(/:id)' , to: 'wallets#cargar_saldo'
    get 'wallets(/:id)' , to: 'wallets#show'
    resources :cards
  end

  get 'rentals/new(/:id)' , to: 'rentals#new' ,as: '/new/rental'
  get 'rentals/find_car(/:id)', to: 'rentals#find_car' ,as: "/find_car"
  get 'rentals/car_tracking(/:id)', to: 'rentals#car_tracking' ,as: "/car_tracking"
  post 'rentals/find_car(/:id)', to: 'rentals#car_unlock'
  resources :rentals

  get 'fines/new(/:id)' , to: 'fines#new' ,as: '/new/fine'
  post 'fines/new(/:id)' , to: 'fines#create' 
  get 'fines/(/:id)' , to: 'fines#index' ,as: '/fines'
  delete '/fines/(/:id)/delete', to: 'fines#destroy', as: '/delete/fine'
  resources :fines 
  
  
  
  # La ruta principal es:
  root "main#index"


  
end

app/models/super_user.rb
class SuperUser < ApplicationRecord
  # Hace uso de la gema BCrypt para encriptar el password
  has_secure_password 

  # Validaciones a nivel base de datos
  validates :dni, presence: true, uniqueness: true, length: { minimum: 7, maximum: 8 },
    format: {
      with: /\A\d+\z/,
      message: :invalid
    }
  validates :name, presence: true
  validates :surname, presence: true
  validates :email, presence: true, uniqueness: true,
    format: {
      with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
      message: :invalid
    }
  validates :phone, presence: true, uniqueness: true, 
    format: {
      with: /\A(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}\z/,
      message: :invalid
    }
  validates :password, length: { minimum: 6 }, unless: proc { |x| x.password.blank? }

    # Callback antes de guardar
  before_save :downcase_attributes

  # Métodos para validar login 
  def is_valid? (password)
    # Un usuario es valido cuando:
    self.authenticate(password) && !self.is_blocked && !self.is_deleted
  end

  # Retorna si el usuario es administrador
  def role?
    if self.is_admin
      "admin"
    else
      "supervisor"
    end
  end

  # Métodos privados
  private

  def downcase_attributes
    # Pasamos los atributos a minúsculas por convención propia
    self.name = name.downcase
    self.surname = surname.downcase
    self.email = email.downcase
  end
end

app/controllers/authentication/sessions_controller.rb
class Authentication::SessionsController < ApplicationController

  def new
  end
  
  def create
    #@user = SuperUser.find_by(dni o email) sino
    @user = User.find_by("dni = :login", {login: params[:login] })
    if(@user.nil?)
      @user = SuperUser.find_by("email = :login", {login: params[:login] })
    end
    # Establece cuando un usuario es válido
    valid_user = @user&.is_valid? params[:password]

    # Comprueba la contraseña que enviamos desde el form con la que está en DB
    # Se usa el authenticate porque está encriptado
    # El & es para decir: si user es nil entonces retorno falso
    if valid_user.nil?
      # El usuario es invalido porque no existe
      redirect_to new_session_path, alert: t('.failed_not_exists') 
    elsif valid_user
      # Cuando el usuario se autentica también creamos la sesión
      if @user.role? == "client" 
        if @user&.driver_license_expirated?
          @user.update_attribute(:must_modify_license, true)
        end
      end
      session[:user_id] = @user.id
      session[:user_role] = @user.role?
      redirect_to main_index_path, notice: t('.created')
    elsif @user&.is_blocked
      # Si el usuario esta bloqueado del sistema
      redirect_to new_session_path, alert: t('.failed_is_blocked')      
    else
      # El usuario es invalido porque introdujo mal los datos
      redirect_to new_session_path, alert: t('.failed_not_valid') 
    end
  end

  def destroy
    # Permite destruir la cookie sesión
    session.delete(:user_id)
    session.delete(:user_role)

    redirect_to main_index_path, notice: t('.destroyed')
  end

  private
  
  def user_params
    # Se quiere que tenga un objeto User antes que todo el contenido de parámetros
    # Luego se hace el permit con todo lo que debe tener
    params.require(:user).permit(:dni, :name, :surname, :email, :phone, :password, :driver_license, :driver_license_expiration, :birthdate)
  end

end 

app/controllers/authentication/super_users_controller.rb
class Authentication::SuperUsersController < ApplicationController

  def index
    @super_users = SuperUser.where(is_deleted: false, is_admin: false)
  end

  def new
    # Para la acción view utilizo una variable de instancia vacia
    # Esta variable de instancia vacia se va a rellenar con el formulario correspondiente
    @super_user = SuperUser.new
  end

def create
  # Se filtran los parámetros instanciando de nuevo
  @super_user = SuperUser.new(super_user_params)

  if @super_user.save
    # Si el super usuario se guarda correctamente
    redirect_to main_index_path, notice: t(".created") 
  else
    # Sino se renderiza de nuevo el formulario new
    # Se pasa como status unprocessable_entity para que TURBO entienda que el formulario no es correcto y se vuelva a renderizar (convención de turbo)
    render :new, status: :unprocessable_entity
  end

end

def block
  super_user
  if (super_user.toggle(:is_blocked).save)
    redirect_to super_users_path, notice: t('.block_toggled')
  else
    redirect_to super_users_path, alert: t('.error_block_toggled')
  end
end

def destroy
  super_user
  super_user.update_attribute(:is_deleted, true)
  redirect_to super_users_path, notice: t('.destroyed')
end

def edit
  super_user
end

def update
  super_user
  if super_user.update(super_user_params)
    redirect_to super_users_path, notice: t('.updated')
  else
    render :edit, status: :unprocessable_entity
  end
end

def show
  super_user
end

private

def super_user
  @super_user ||= SuperUser.find(params[:id])
end

def super_user_params
  # Se quiere que tenga un objeto super_user antes que todo el contenido de parámetros
  # Luego se hace el permit con todo lo que debe tener
  params.require(:super_user).permit(:dni, :name, :surname, :email, :phone, :password)
end

end

app/controllers/authentication/users_controller.rb
class Authentication::UsersController < ApplicationController

    def index
      # Usuarios activos
      @users = User.where(is_deleted: :false, is_accepted: true)
    end

    def pre_registered
      # Usuarios pre-registrados (por ser aprobados o rechazados)
      @users = User.where(is_deleted: :false, is_accepted: false)
      #TRAER TABLA DONDE IS_ACCEPTED: FALSE

        # VIEW --> BOTON APROBAR -> approve --> UserMail.approve
        # VIEW --> BOTON RECHAZAR -> reject --> UserMail.reject
    end

    def accept
      user
      @amount = 400
      user.update_attribute(:pending_license_modification, false)
      user.update_attribute(:must_modify_license, false)         
      user.wallet.update_attribute(:balance, @amount)
      user.update_attribute(:is_accepted, true)
      UserMailer.with(user: user, amount: @amount).accept.deliver_later
      redirect_to pre_registered_path, notice: t('.accepted')
    end

    def reject
      # Enviar mail de por qué rechaza el pre-registro
      UserMailer.with(user: user, motive: params[:motive], observations: params[:observations]).reject.deliver_later
      ##user.destroy
      user.rejected_motive = params[:motive]
      user.rejected_message = params[:observations]
      user.update_attribute(:pending_license_modification, false)
      user.update_attribute(:must_modify_license, true)      
      if user.save
        redirect_to pre_registered_path, notice: t('.rejected')
      else
        flash.now[:notice] = t('unexpected_error')
        render :pre_registered, status: :unprocessable_entity
      end

    end

    def new
      # Para la acción view utilizo una variable de instancia vacia
      # Esta variable de instancia vacia se va a rellenar con el formulario correspondiente
      @user = User.new
    end
    
    def create
      # Se filtran los parámetros instanciando de nuevo
      @user = User.new(user_params)
      @user.wallet = Wallet.new(balance: 0)
      if @user.save
        # Envio mail de bienvenida
        UserMailer.with(user: @user).welcome.deliver_later
        # Si el usuario se guarda correctamente
        redirect_to main_index_path, notice: t(".created")
      else
        # Sino se renderiza de nuevo el formulario new
        # Se pasa como status unprocessable_entity para que TURBO entienda que el formulario no es correcto y se vuelva a renderizar (convención de turbo)
        render :new, status: :unprocessable_entity
      end

    end

    def edit
      user
    end
    
    def update
      user
      if user.authenticate(user_actual_password_param[:actual_password])
        if user.update(user_edit_params)
          clear_rejected_messages
          redirect_to show_client_path(user.id), notice: t('.updated')
        else
          render :edit, status: :unprocessable_entity
        end
      else
        flash.now[:error] = t('.invalid_actual_password_validation')
        flash.now.alert = t('.invalid_actual_password')
        render :edit, status: :unprocessable_entity
      end
    end

    def edit_password
      user
    end

    def update_password
      user
      if user.authenticate(user_actual_password_param[:actual_password])
        if user.update(user_edit_password_params)
          redirect_to show_client_path(user.id), notice: t('.updated')
        else
          render :edit_password, status: :unprocessable_entity
        end
      else
        flash.now[:error] = t('.invalid_actual_password_validation')
        flash.now.alert = t('.invalid_actual_password')
        render :edit_password, status: :unprocessable_entity
      end      
    end

    def edit_license
      user
    end

    def update_license
      user
      if user.authenticate(user_actual_password_param[:actual_password])
        if user.update(user_edit_license_params)
          user.update_attribute(:pending_license_modification, true)
          redirect_to show_client_path(user.id), notice: t('.updated')
        else
          render :edit_license, status: :unprocessable_entity
        end
      else
        flash.now[:error] = t('.invalid_actual_password_validation')
        flash.now.alert = t('.invalid_actual_password')
        render :edit_license, status: :unprocessable_entity
      end      
    end

    def accept_license
      user
      UserMailer.with(user: user).accept_license.deliver_later
      user.update_attribute(:pending_license_modification, false)
      user.update_attribute(:must_modify_license, false)
      clear_rejected_messages
      redirect_to clients_path, notice: t('.accepted')      
    end
    
    def reject_license
      user
      UserMailer.with(user: user).reject_license.deliver_later
      user.update_attribute(:pending_license_modification, false)
      user.update_attribute(:must_modify_license, true)
      clear_rejected_messages
      redirect_to clients_path, alert: t('.rejected')            
    end

    def block
      user
      if (user.toggle(:is_blocked).save)
        user.is_blocked ? UserMailer.with(user: @user).block.deliver_later : UserMailer.with(user: @user).unblock.deliver_later
        redirect_to clients_path, notice: t('.block_toggled')
      else
        redirect_to clients_path, alert: t('.error_block_toggled')
      end
    end
  
    def destroy
      user
      user.update_attribute(:is_deleted, true)
      redirect_to clients_path, notice: t('.destroyed')
    end

    def show
      user
    end

    private

    def user
      @user ||= User.find(params[:id])
    end

    def user_params
      # Se quiere que tenga un objeto User antes que todo el contenido de parámetros
      # Luego se hace el permit con todo lo que debe tener
      params.require(:user).permit(:dni, :name, :surname, :email, :phone, :password, :driver_license, :driver_license_expiration, :birthdate)
    end

    def user_edit_params
      params.require(:user).permit(:dni, :name, :surname, :email, :phone, :birthdate)
    end

    def user_edit_password_params
      params.require(:user).permit(:password)
    end

    def user_edit_license_params
      params.require(:user).permit(:driver_license, :driver_license_expiration)
    end

    def user_actual_password_param
      params.require(:user).permit(:actual_password)
    end

    def clear_rejected_messages
      user.update_attribute(:rejected_motive, "")
      user.update_attribute(:rejected_message, "")
    end
end 

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    # Antes de cualquier acción, se llama a este método
    before_action :set_current_user 

    private

    def set_current_user
      # Busca al usuario por id y si no lo encuentra no lanza excepción
      # Atributo disponible a toda la aplicación
      # Solo se realiza si existe una sesión
      # Lo almacena como usuario actual
      if session[:user_role] == "client"
        Current.user = User.find_by(id: session[:user_id]) if session[:user_id] 
        Current.role = Current.user.role? if session[:user_role] 
      else
        Current.user = SuperUser.find_by(id: session[:user_id]) if session[:user_id] 
        Current.role = Current.user.role? if session[:user_role] 
      end
    end

  end
end

app/views/authentication/super_users/_form.html.erb
<!-- Registro de super usuarios -->
<section class="md:grid md:grid-cols-2 md:gap-6">
  <article class="mt-1 md:col-span-2 md:mt-1">
    <%= form_with(model: super_user) do |form| %>
      <div class="overflow-hidden shadow sm:rounded-md">
        <div class="bg-white px-4 sm:mt-4">
          <div class="grid grid-cols-6 gap-4">

            <%# Input para nombre %>
            <div class="col-span-6 sm:col-span-3">
              <%= form.label :name, class: "block font-semibold" %>
              <%= form.text_field :name, 
                placeholder: t('.placeholder_name'),
                class: "border w-full h-5 px-3 py-5 mt-1 focus:z-10 focus:border-orange-700 focus:outline-none focus:ring-orange-700 rounded-md" %>
              <% if super_user.errors.full_messages_for(:name).each  do |error| %>
                  <ul class="list-disc list-inside">
                    <li class="text-xs text-red-500">
                      <%= error %>
                    </li>
                  </ul>
                <% end %>
              <% end %>
              </div>

            <%# Input para apellido %>
            <div class="col-span-6 sm:col-span-3">
              <%= form.label :surname, class: "block font-semibold" %>
              <%= form.text_field :surname, 
                placeholder: t('.placeholder_surname'),
                class: "border w-full h-5 px-3 py-5 mt-1 focus:z-10 focus:border-orange-700 focus:outline-none focus:ring-orange-700 rounded-md" %>
              <% if super_user.errors.full_messages_for(:surname).each  do |error| %>
                  <ul class="list-disc list-inside">
                    <li class="text-xs text-red-500">
                      <%= error %>
                    </li>
                  </ul>
                <% end %>
              <% end %>
            </div>

            <%# Input para phone %>
            <div class="col-span-6 sm:col-span-3">
              <%= form.label :phone, class: "block font-semibold" %>
              <%= form.text_field :phone, 
                placeholder: t('.placeholder_phone'),
                class: "border w-full h-5 px-3 py-5 mt-1 focus:z-10 focus:border-orange-700 focus:outline-none focus:ring-orange-700 rounded-md" %>
              <% if super_user.errors.full_messages_for(:phone).each  do |error| %>
                  <ul class="list-disc list-inside">
                    <li class="text-xs text-red-500">
                      <%= error %>
                    </li>
                  </ul>
                <% end %>
              <% end %>
            </div>

            <%# Input para dni %>
            <div class="col-span-6 sm:col-span-3">
              <%= form.label :dni, class: "block font-semibold" %>
              <%= form.text_field :dni, 
                placeholder: t('.placeholder_dni'),
                class: "border w-full h-5 px-3 py-5 mt-1 focus:z-10 focus:border-orange-700 focus:outline-none focus:ring-orange-700 rounded-md" %>
              <% if super_user.errors.full_messages_for(:dni).each  do |error| %>
                  <ul class="list-disc list-inside">
                    <li class="text-xs text-red-500">
                      <%= error %>
                    </li>
                  </ul>
                <% end %>
              <% end %>
            </div>

            <%# Input para email %>
            <div class="col-span-6 sm:col-span-3">
              <%= form.label :email, class: "block font-semibold" %>
              <%= form.email_field :email, 
                placeholder: t('.placeholder_email'),
                class: "border w-full h-5 px-3 py-5 mt-1 focus:z-10 focus:border-orange-700 focus:outline-none focus:ring-orange-700 rounded-md" %>
              <% if super_user.errors.full_messages_for(:email).each  do |error| %>
                  <ul class="list-disc list-inside">
                    <li class="text-xs text-red-500">
                      <%= error %>
                    </li>
                  </ul>
                <% end %>
              <% end %>
            </div>

            <%# Input para password %>
            <div class="col-span-6 sm:col-span-3">
              <%= form.label :password, class: "block font-semibold" %>
              <%= form.password_field :password, 
                placeholder: t('.placeholder_password'),
                class: "border w-full h-5 px-3 py-5 mt-1 focus:z-10 focus:border-orange-700 focus:outline-none focus:ring-orange-700 rounded-md" %>
              <% if super_user.errors.full_messages_for(:password).each  do |error| %>
                  <ul class="list-disc list-inside">
                      <li class="text-xs text-red-500">
                        <%= error %>
                    </li>
                  </ul>
                <% end %>
              <% end %>
            </div>

          </div>
        </div>
        <div class="flex justify-center bg-gray-50 text-right sm:px-6 mt-4">
          <%# Botón de submit %>
          <%= button_tag(type: "submit", 
            class: "mt-2 sm:mt-0 mb-1 text-orange-100 font-bold bg-orange-500 py-2 px-2 rounded hover:brightness-110 border-2 border-black focus:z-10 focus:border-orange-900 focus:outline-none focus:ring-orange-900") do %>
            <%= content_tag(:strong, t('.submit')) %>
          <% end %>
        </div>
      </div>
    <% end %>
  </article>
</section>

app/views/authentication/super_users/_table.html.erb
<section class="m-8">
  <%# Se puede agregar algun elemento por aqui %>
  <article class="overflow-auto rounded-lg shadow hidden md:block select-none">
    <table class="w-full">
      <thead class="text-xs uppercase bg-gray-800 text-gray-200">
        <tr class="border-2 border-black">
          <th class="w-20 p-3 text-sm font-bold tracking-wide text-left whitespace-nowrap"><%= t('.state') %></th>
          <th class="w-20 p-3 text-sm font-bold tracking-wide text-left whitespace-nowrap"><%= t('.name') %></th>
          <th class="w-20 p-3 text-sm font-bold tracking-wide text-left whitespace-nowrap"><%= t('.surname') %></th>
          <th class="w-20 p-3 text-sm font-bold tracking-wide text-left whitespace-nowrap"><%= t('.dni') %></th>
          <th class="w-20 p-3 text-sm font-bold tracking-wide text-left whitespace-nowrap"><%= t('.email') %></th>
          <th class="w-20 p-3 text-sm font-bold tracking-wide text-left whitespace-nowrap"><%= t('.phone') %></th>
          <th class="w-20 p-3 text-sm font-bold tracking-wide text-left whitespace-nowrap"><%= t('.actions') %></th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-100">  
        <% if super_users.count > 0 %>
          <%# En caso de haber usuarios %>
          <% super_users.each do |super_user| %>
            <tr class="<%= class_names('hover:bg-gray-400', {'bg-red-200': super_user.is_blocked}) %>">
              <td class="p-3 text-sm text-gray-700 whitespace-nowrap uppercase">
                <span class="<%= class_names('p-1.5 text-xs font-medium uppercase tracking-wider text-gray-200 rounded-lg bg-green-400 border-2 border-black', {'bg-red-500': super_user.is_blocked}) %>"><%= super_user.is_blocked ? t('.blocked') : t('.non_blocked') %></span>
              </td>
              <td class="p-3 text-sm text-gray-700 whitespace-nowrap uppercase"><%= super_user.name %></td>
              <td class="p-3 text-sm text-gray-700 whitespace-nowrap uppercase"><%= super_user.surname %></td>
              <td class="p-3 text-sm text-gray-700 whitespace-nowrap uppercase"><%= super_user.dni %></td>
              <td class="p-3 text-sm text-gray-700 whitespace-nowrap uppercase"><%= super_user.email %></td>
              <td class="p-3 text-sm text-gray-700 whitespace-nowrap uppercase"><%= super_user.phone %></td>
              <td class="p-3 text-gray-700 whitespace-nowrap uppercase">
                <%= link_to t('.view_details'), super_user_path(super_user), class: "p-1.5 focus:outline-none text-white bg-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:ring-yellow-300 font-medium rounded-lg text-sm dark:focus:ring-yellow-900 border border-black" %>
                <%= link_to t('.edit'), edit_super_user_path(super_user), class: "p-1.5 focus:outline-none text-white bg-blue-400 hover:bg-blue-500 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm dark:focus:ring-blue-900 border border-black" if Current.user&.role? == "admin" %>
                <%= button_to t('.block'), block_supervisor_path(super_user.id), method: :patch, form_class: "contents", class: "inline p-1 focus:outline-none text-white bg-violet-400 hover:bg-violet-500 focus:ring-4 focus:ring-violet-300 font-medium rounded-lg text-sm dark:focus:ring-violet-900 border border-black uppercase" if Current.user&.role? == "admin" %>
                <%= link_to t('.delete'), delete_supervisor_path(super_user.id), data: {
                turbo_method: :delete,
                turbo_confirm: t('common.confirm')
                }, class: "p-1.5 focus:outline-none text-white bg-red-400 hover:bg-red-500 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm dark:focus:ring-red-900 border border-black" if Current.user&.role? == "admin" %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <%# En caso de no haber usuarios %>
          <tr>
            <td class="p-3 text-sm text-gray-700 whitespace-nowrap uppercase"> <%= t('.no_records_available') %> </td>
          </tr>
        <% end %>
      </tbody>  
    </table>
  </article>
  
  <%# Para la vista mobile %>
  <article class="grid grid-cols-1 sm:grid-cols-2 gap-4 md:hidden">
    <% if super_users.count > 0 %>
      <%# En caso de haber autos %>
      <% super_users.each do |super_user| %>
        <div class="space-y-3 p-4 rounded-lg shadow border-2 border-black bg-gray-800">
          <div class="flex items-center space-x-2 text-sm flex-wrap gap-2">
              <div>
                <span class="<%= class_names('p-1.5 text-xs font-medium uppercase tracking-wider text-gray-200 rounded-lg bg-green-400 border-2 border-black whitespace-nowrap', {'bg-red-500': super_user.is_blocked}) %>"><%= super_user.is_blocked ? t('.blocked') : t('.non_blocked') %></span>
                </span>
              </div>
          </div>
          <div class="text-sm text-gray-200 flex flex-col">
            <p>
              <span class="text-sm text-gray-200 uppercase font-bold"><%= t('.name') %>:</span>
              <span class="text-sm text-gray-200 uppercase"><%= super_user.name %></span>
            </p>
            <p>
              <span class="text-sm text-gray-200 uppercase font-bold"><%= t('.surname') %>:</span>
              <span class="text-sm text-gray-200 uppercase"><%= super_user.surname %></span>
            </p>
            <p>
              <span class="text-sm text-gray-200 uppercase font-bold"><%= t('.dni') %>:</span>
              <span class="text-sm text-gray-200 uppercase"><%= super_user.dni %></span>
            </p>
            <p>
              <span class="text-sm text-gray-200 uppercase font-bold"><%= t('.email') %>:</span>
              <span class="text-sm text-gray-200 uppercase"><%= super_user.email %></span>
            </p>
            <p>
              <span class="text-sm text-gray-200 uppercase font-bold"><%= t('.phone') %>:</span>
              <span class="text-sm text-gray-200 uppercase"><%= super_user.phone %></span>
            </p>
          </div>
          <div class="flex flex-wrap gap-2 uppercase">
            <%= link_to t('.view_details'), super_user_path(super_user), class: "p-1.5 focus:outline-none text-white bg-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:ring-yellow-300 font-medium rounded-lg text-sm dark:focus:ring-yellow-900 border border-black" %>
            <%= link_to t('.edit'), edit_super_user_path(super_user), class: "p-1.5 focus:outline-none text-white bg-blue-400 hover:bg-blue-500 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm dark:focus:ring-blue-900 border border-black" if Current.user&.role? == "admin" %>
            <%= button_to t('.block'), block_supervisor_path(super_user.id), method: :patch, form_class: "contents", class: "inline p-1 focus:outline-none text-white bg-violet-400 hover:bg-violet-500 focus:ring-4 focus:ring-violet-300 font-medium rounded-lg text-sm dark:focus:ring-violet-900 border border-black uppercase" if Current.user&.role? == "admin" %>
            <%= link_to t('.delete'), delete_supervisor_path(super_user.id), data: {
            turbo_method: :delete,
            turbo_confirm: t('common.confirm')
            }, class: "p-1.5 focus:outline-none text-white bg-red-400 hover:bg-red-500 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm dark:focus:ring-red-900 border border-black" if Current.user&.role? == "admin" %>
          </div>
        </div>
      <% end %>
    <% else %>
      <%# En caso de no haber usuarios %>
      <h4 class="p-3 text-sm text-gray-700 whitespace-nowrap uppercase"> <%= t('.no_records_available') %></h4>
    <% end %>
  </article>
</section>

app/views/authentication/super_users/edit.html.erb
<%= render 'form', super_user: @super_user %>

app/views/authentication/super_users/index.html.erb
<section class="mx-4 mb-2 p-4 bg-gray-800 text-gray-200 rounded-b-lg border-2 border-black">
  <h4 class="text-2xl uppercase text-center">
    <%= t('.title') %>
  </h4>
</section>

<% if Current.user&.role? == "admin" %>
  <%# Renderizo tabla %>
  <%= render 'table', super_users: @super_users %>
<% end %>

app/views/authentication/super_users/new.html.erb
<%= render 'form', super_user: @super_user %>