config/routes.rb
Rails.application.routes.draw do
  resources :cars do 
    member do
      put :visible
    end
  end
  # Reportes
  resources :reports
  patch '/reports/:id/reject', to: 'reports#reject', as: '/reject/report'
  patch '/reports/:id/accept', to: 'reports#accept', as: '/accept/report'
  
  ##get '/reports/:id/create_report_message', to: 'reports#create_report_message', as: '/create_report_message/report'
  

  resources :cars_usage_histories,only: [:show], path: '/history', path_names: { show: '/' }
  # Existe una jerarquia top-down

  # Se quiere organizar grupos de controllers bajo un namespace
  # El directorio de ellos se encuentra en app/controllers/authentication
  # Ver CAP 2.6 guides.rubyonrails.org/routing.html
  # No se quiere que el namespace figure en la ruta, entonces se pasa vacio al path
  # Sino figuraria cómo /authentication/users/new 
  namespace :authentication, path: "", as: "" do
    # Super usuarios
    resources :super_users, only: [:index, :new, :create, :edit, :update, :show]
    patch '/super_users/:id/block', to: 'super_users#block', as: '/block/supervisor'
    delete '/super_users/:id/delete', to: 'super_users#destroy', as: '/delete/supervisor'

    # Usuarios
    resources :users, only: [:edit, :update]
    resources :users, only: [:new, :create], path: '/register', path_names: { new: '/' }
    get '/users', to: 'users#index', as: '/clients'
    get '/pre_registered', to: 'users#pre_registered', as: '/pre_registered'
    patch '/users/:id/block', to: 'users#block', as: '/block/client'
    delete '/users/:id/delete', to: 'users#destroy', as: '/delete/client'
    patch '/users/:id/accept', to: 'users#accept', as: '/accept/client'
    delete '/users/:id/reject', to: 'users#reject', as: '/reject/client'
    get '/users/:id/edit_password', to: 'users#edit_password', as: '/edit_password/user'
    patch '/users/:id/edit_password', to: 'users#update_password', as: '/update_password/user'
    get '/users/:id/edit_license', to: 'users#edit_license', as: '/edit_license/user'
    patch '/users/:id/edit_license', to: 'users#update_license', as: '/update_license/user'
    patch '/users/:id/accept_license', to: 'users#accept_license', as: '/accept_license/user'
    patch '/users/:id/reject_license', to: 'users#reject_license', as: '/reject_license/user'
    get '/users/:id/reject_message', to: 'users#reject_message', as: '/reject_message/client'
    get '/users/:id/show', to: 'users#show', as: '/show/client'
    
    # Sesiones
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
  end

  resources :main, only: [:index]
  

  #ruteo de la wallet management
  namespace :wallet_management, path: "", as:"" do
    resources :wallets, only: [:show] 
    put 'wallets(/:id)' , to: 'wallets#cargar_saldo'
    get 'wallets(/:id)' , to: 'wallets#show'
    resources :cards
  end

  get 'rentals/new(/:id)' , to: 'rentals#new' ,as: '/new/rental'
  get 'rentals/find_car(/:id)', to: 'rentals#find_car' ,as: "/find_car"
  get 'rentals/car_tracking(/:id)', to: 'rentals#car_tracking' ,as: "/car_tracking"
  post 'rentals/find_car(/:id)', to: 'rentals#car_unlock'
  resources :rentals

  get 'fines/new(/:id)' , to: 'fines#new' ,as: '/new/fine'
  post 'fines/new(/:id)' , to: 'fines#create' 
  get 'fines/(/:id)' , to: 'fines#index' ,as: '/fines'
  delete '/fines/(/:id)/delete', to: 'fines#destroy', as: '/delete/fine'
  resources :fines 
  
  
  
  # La ruta principal es:
  root "main#index"


  
end

app/views/shared/_flash.html.erb
<!-- Tarjeta flash de notificaciones -->
<% if alert || notice %>
  <% color = alert ? 'bg-red-400' : 'bg-green-400' %>
  <div class="fixed top-0 inset-x-0 mx-4 mt-24 z-30 pointer-events-none">
    <div class="flex flex-col items-end space-y-4">
      <div data-controller="alert" data-alert-dismiss-after-value="3500" data-alert-show-class="translate-x-0 opacity-100" data-alert-hide-class="translate-x-full opacity-0" class="ease-in-out duration-500 max-w-sm w-full shadow-lg rounded px-4 py-3 relative <%= color %> text-white pointer-events-auto translate-x-0 opacity-100 border-2 border-black font-bold">
        <div class="p-2">
          <div class="flex items-start">
            <div class="ml-3 w-0 flex-1 pt-0.5">
              <p class="text-sm leading-5 font-medium">
                <%= alert || notice %>
              </p>
            </div>
            <div class="ml-4 flex-shrink-0 flex">
              <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<!-- Header de la aplicación -->

<header class="bg-orange-700 flex justify-between items-center py-2 px-2 rounded-b-lg mx-2 border-2 border-black print:hidden" data-controller="menu">
  
  <!-- Logo de la aplicación -->
  <%= link_to root_path do %>
    <div class="flex flex-col bg-orange-300 py-1 px-2 rounded hover:brightness-110 transition-color duration-200 delay-50 border border-black">
      <h1 class="text-2xl font-bold text-zinc-900"><%= t('app_name') %></h1>
      <h2 class="text-xs font-bold text-orange-600"><%= t('app_subtitle').upcase %></h2>
    </div>
  <% end %>
  
  <!-- Menu desktop -->
  <div class="hidden  sm:flex sm:flex-wrap sm:gap-1 ">
      <%= render partial: 'shared/items' %>
  </div>

  <!-- Menu mobile -->

  <!-- Menu cerrado -->
  <button class="sm:hidden bg-orange-300 rounded hover:brightness-110 border border-black" data-action="click->menu#toggle">
    <%= image_tag 'icons/menu.svg', width: 35, height: 35 %>
  </button>

  <!-- Menu abierto -->
  <div class="gap-4 sm:hidden absolute bg-orange-700 top-0 right-0 shadow h-full flex flex-col min-w-[45%] overflow-y-scroll ease-in-out duration-200 p-5 translate-x-full mt-2 border-2 border-black" style="z-index: 2000;" data-menu-target="items">
    <div class="flex flex-col items-start">
      <button class="mb-4 bg-orange-300 rounded hover:brightness-110 border border-black" data-action="click->menu#toggle">
        <%= image_tag 'icons/close.svg', width: 35, height: 35 %>
      </button>
    </div>
    <%= render partial: 'shared/items' %>
  </div>

</header>

app/views/shared/_items.html.erb
<!-- Indicador de usuario -->

<% if Current.user %>
  <p class="inline p-2 border-2 border-black text-center text-lime-500 font-bold"><%= Current.user&.role?.upcase + ": " + Current.user&.name&.capitalize%></p>
<% end %>

<!-- Botones del header -->
<% if Current.user&.role? == 'client' && Current.user.rentals.find_by(is_active:true) %>
  <% if Current.user.rentals.find_by(is_active:true).car.is_rented && Current.user.rentals.find_by(is_active:true).car.is_unlocked %>
    <%= link_to t('.car_tracking'), car_tracking_path(Current.user.rentals.find_by(is_active:true).id), class: "mx-1 text-white font-bold bg-green-500 py-2 px-2 rounded hover:brightness-110 border border-black focus:border-orange-900 focus:outline-none focus:ring-orange-900" %>
  <% else %>
    <%= link_to t('.car_tracking'), find_car_path(Current.user.rentals.find_by(is_active:true).id), class: "mx-1 text-white font-bold bg-green-500 py-2 px-2 rounded hover:brightness-110 border border-black focus:border-orange-900 focus:outline-none focus:ring-orange-900" %>
  <% end %>
<% end %>
<%= link_to t('.home'), root_path, class: "mx-1 text-orange-600 font-bold bg-orange-300 py-2 px-2 rounded hover:brightness-110 border border-black focus:border-orange-900 focus:outline-none focus:ring-orange-900" %>
<%= link_to t('.view_cars'), cars_path, class: "mx-1 text-orange-600 font-bold bg-orange-300 py-2 px-2 rounded hover:brightness-110 border border-black focus:border-orange-900 focus:outline-none focus:ring-orange-900" if Current.user&.role? == "client" && Current.user&.is_accepted && !(Current.user&.must_modify_license || Current.user&.pending_license_modification )%>
<%= link_to t('.view_profile'), show_client_path(Current.user.id), class: "mx-1 text-orange-600 font-bold bg-orange-300 py-2 px-2 rounded hover:brightness-110 border border-black focus:border-orange-900 focus:outline-none focus:ring-orange-900" if Current.user&.role? == "client" %>
<%= link_to t('.register'), new_user_path, class: "mx-1 text-orange-600 font-bold bg-orange-300 py-2 px-2 rounded hover:brightness-110 border border-black focus:border-orange-900 focus:outline-none focus:ring-orange-900" unless Current.user %>
<%= link_to t('.login'), new_session_path, class: "mx-1 text-orange-100 font-bold bg-orange-500 py-2 px-2 rounded hover:brightness-110 border-2 border-black focus:z-10 focus:border-orange-900 focus:outline-none focus:ring-orange-900" unless Current.user %>
<%= link_to t('.view_wallet'), wallet_path(Current.user.id), class: "mx-1 text-orange-100 font-bold bg-orange-500 py-2 px-2 rounded hover:brightness-110 border-2 border-black focus:z-10 focus:border-orange-900 focus:outline-none focus:ring-orange-900" if Current.user&.role? == 'client' && Current.user&.is_accepted %> 
<%= link_to t('.logout'), session_path(Current.user.id), data: {
  turbo_method: :delete,
  turbo_confirm: t('common.confirm')
}, class: "mx-1 text-orange-600 font-bold bg-orange-300 py-2 px-2 rounded hover:brightness-110 border border-black focus:border-orange-900 focus:outline-none focus:ring-orange-900" if Current.user %>

app/views/shared/_license_message.html.erb
<div id="license_message" class="z-30 fixed left-0 m-4 p-4 border-2 font-bold border-black bg-red-400 flex gap-4 items-start w-96 bg-opacity-70 pointer-events-none">
  <ul class="flex flex-col gap-2 text-white text-sm break-normal text-opacity-80 bg-opacity-90">
    <li><%= Current.user.name.capitalize %></li>
    <% if Current.user.pending_license_modification %>
      <li>Tus nuevos datos de licencia de conducir fueron enviados para que un supervisor los revise, debe esperar su respuesta</li>
    <% else %>
      <li>Debes modificar los datos de la licencia de conducir debido a que es inválida o ha expirado</li>
    <% end %>
  </ul>
  <a href="#" onclick="hide(license_message);" class="hover:bg-white rounded-full p-1 pointer-events-auto">X</a>
</div>

<script>
  function hide(hideID) 
  {
    hideID.style.display = "none"; 
  }
</script>

app/views/shared/_not_accepted_message.html.erb
<div id="message" class="z-30 fixed right-0 bottom-0 m-4 p-4 border-2 font-bold border-black bg-red-400 flex gap-4 items-start w-96 bg-opacity-70 pointer-events-none">
  <ul class="flex flex-col gap-2 text-white text-sm break-normal text-opacity-80 bg-opacity-90">
    <li><%= Current.user.name.capitalize %></li>
    <% if Current.user.rejected_motive == "" %>
      <li>Debes esperar a que un supervisor te acepte</li>
    <% else %>
      <li>El supervisor ha rechazado tu registro, debido a <%= Current.user.rejected_motive.downcase %>, puedes modificar tus datos desde el botón "Ver perfil"</li>
      <% if Current.user.rejected_message != "" %>
        <li>Las observaciónes que ha hecho son: <%= Current.user.rejected_message.downcase %></li>
      <% end %>
    <% end %>
  </ul>
  <a href="#" onclick="hide(message);" class="hover:bg-white rounded-full p-1 pointer-events-auto">X</a>
</div>

<script>
  function hide(hideID) 
  {
    hideID.style.display = "none"; 
  }
</script>

app/views/shared/_tool_items.html.erb
<% if Current.user&.role? == "admin" || Current.user&.role? == "supervisor"%>
  <div class="flex gap-2 overflow-x-auto p-2 mx-4 whitespace-nowrap bg-gray-800">
    <%= link_to t('shared.items.view_cars'), cars_path, class: "font-bold bg-gray-400 px-2 py-2 rounded-full hover:bg-gray-200 hover:text-gray-800 border border-black focus:z-10 focus:border-gray-900 focus:outline-none focus:ring-gray-900" %>
    <%= link_to t('shared.items.add_car'), new_car_path, class: "font-bold bg-gray-400 px-2 py-2 rounded-full hover:bg-gray-200 hover:text-gray-800 border border-black focus:z-10 focus:border-gray-900 focus:outline-none focus:ring-gray-900" if Current.user&.role? == "admin" %>
    <%= link_to t('shared.items.view_supervisors'), super_users_path, class: "font-bold bg-gray-400 px-2 py-2 rounded-full hover:bg-gray-200 hover:text-gray-800 border border-black focus:z-10 focus:border-gray-900 focus:outline-none focus:ring-gray-900" if Current.user&.role? == "admin" %>
    <%= link_to t('shared.items.add_supervisor'), new_super_user_path, class: "font-bold bg-gray-400 px-2 py-2 rounded-full hover:bg-gray-200 hover:text-gray-800 border border-black focus:z-10 focus:border-gray-900 focus:outline-none focus:ring-gray-900" if Current.user&.role? == "admin" %>
    <%= link_to t('shared.items.view_users'), clients_path, class: "font-bold bg-gray-400 px-2 py-2 rounded-full hover:bg-gray-200 hover:text-gray-800 border border-black focus:z-10 focus:border-gray-900 focus:outline-none focus:ring-gray-900" if Current.user&.role? == "supervisor" %>
    <%= link_to t('shared.items.view_pre_registered'), pre_registered_path, class: "font-bold bg-gray-400 px-2 py-2 rounded-full hover:bg-gray-200 hover:text-gray-800 border border-black focus:z-10 focus:border-gray-900 focus:outline-none focus:ring-gray-900" if Current.user&.role? == "supervisor" %>
    <%= link_to t('shared.items.view_reports'), reports_path, class: "font-bold bg-gray-400 px-2 py-2 rounded-full hover:bg-gray-200 hover:text-gray-800 border border-black focus:z-10 focus:border-gray-900 focus:outline-none focus:ring-gray-900" if Current.user&.role? == "supervisor" %>
  </div>
<% end %>