config/routes.rb
Rails.application.routes.draw do
  resources :cars do 
    member do
      put :visible
    end
  end
  # Reportes
  resources :reports
  patch '/reports/:id/reject', to: 'reports#reject', as: '/reject/report'
  patch '/reports/:id/accept', to: 'reports#accept', as: '/accept/report'
  
  ##get '/reports/:id/create_report_message', to: 'reports#create_report_message', as: '/create_report_message/report'
  

  resources :cars_usage_histories,only: [:show], path: '/history', path_names: { show: '/' }
  # Existe una jerarquia top-down

  # Se quiere organizar grupos de controllers bajo un namespace
  # El directorio de ellos se encuentra en app/controllers/authentication
  # Ver CAP 2.6 guides.rubyonrails.org/routing.html
  # No se quiere que el namespace figure en la ruta, entonces se pasa vacio al path
  # Sino figuraria cómo /authentication/users/new 
  namespace :authentication, path: "", as: "" do
    # Super usuarios
    resources :super_users, only: [:index, :new, :create, :edit, :update, :show]
    patch '/super_users/:id/block', to: 'super_users#block', as: '/block/supervisor'
    delete '/super_users/:id/delete', to: 'super_users#destroy', as: '/delete/supervisor'

    # Usuarios
    resources :users, only: [:edit, :update]
    resources :users, only: [:new, :create], path: '/register', path_names: { new: '/' }
    get '/users', to: 'users#index', as: '/clients'
    get '/pre_registered', to: 'users#pre_registered', as: '/pre_registered'
    patch '/users/:id/block', to: 'users#block', as: '/block/client'
    delete '/users/:id/delete', to: 'users#destroy', as: '/delete/client'
    patch '/users/:id/accept', to: 'users#accept', as: '/accept/client'
    delete '/users/:id/reject', to: 'users#reject', as: '/reject/client'
    get '/users/:id/edit_password', to: 'users#edit_password', as: '/edit_password/user'
    patch '/users/:id/edit_password', to: 'users#update_password', as: '/update_password/user'
    get '/users/:id/edit_license', to: 'users#edit_license', as: '/edit_license/user'
    patch '/users/:id/edit_license', to: 'users#update_license', as: '/update_license/user'
    patch '/users/:id/accept_license', to: 'users#accept_license', as: '/accept_license/user'
    patch '/users/:id/reject_license', to: 'users#reject_license', as: '/reject_license/user'
    get '/users/:id/reject_message', to: 'users#reject_message', as: '/reject_message/client'
    get '/users/:id/show', to: 'users#show', as: '/show/client'
    
    # Sesiones
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
  end

  resources :main, only: [:index]
  

  #ruteo de la wallet management
  namespace :wallet_management, path: "", as:"" do
    resources :wallets, only: [:show] 
    put 'wallets(/:id)' , to: 'wallets#cargar_saldo'
    get 'wallets(/:id)' , to: 'wallets#show'
    resources :cards
  end

  get 'rentals/new(/:id)' , to: 'rentals#new' ,as: '/new/rental'
  get 'rentals/find_car(/:id)', to: 'rentals#find_car' ,as: "/find_car"
  get 'rentals/car_tracking(/:id)', to: 'rentals#car_tracking' ,as: "/car_tracking"
  post 'rentals/find_car(/:id)', to: 'rentals#car_unlock'
  resources :rentals

  get 'fines/new(/:id)' , to: 'fines#new' ,as: '/new/fine'
  post 'fines/new(/:id)' , to: 'fines#create' 
  get 'fines/(/:id)' , to: 'fines#index' ,as: '/fines'
  delete '/fines/(/:id)/delete', to: 'fines#destroy', as: '/delete/fine'
  resources :fines 
  
  
  
  # La ruta principal es:
  root "main#index"


  
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :reports, dependent: :destroy
  has_many :rental, dependent: :destroy
  has_many :fine, dependent: :destroy
  has_many :car_usage_history, dependent: :destroy
  # Imagen del autos
  has_one_attached :photo, dependent: :destroy
  # Validaciones a nivel base de datos
  validates :brand, presence: true
  validates :color, presence: true
  validates :patent, presence: true, uniqueness: true
  validate :validate_patent_argentina
  validates :vehicle_number, presence: true, uniqueness: true
  validates :model, presence: true
  validates :photo, presence: true
  validate :validate_photo_filetype
  # Callback antes de guardar
  before_save :downcase_attributes

  private
  
  def downcase_attributes
    # Pasamos los atributos a minúsculas por convención propia
    self.brand = brand.downcase
    self.color = color.downcase
    self.patent = patent.downcase
    self.model = model.downcase
  end

  def validate_photo_filetype
    # Valida el formato del archivo adjunto
    if photo.attached? && !photo.content_type.in?(%w(image/jpeg image/png))
      errors.add(:photo, :bad_photo_type, type1: ".jpg", type2: ".png")
    end
  end

  def validate_patent_argentina
    # 3 letras y 3 números
    old_patent_regex = /\A[a-zA-Z]{3}[\d]{3}\z/
    # 2 letras, 3 números y 2 letras
    new_patent_regex = /\A[a-zA-Z]{2}[\d]{3}[a-zA-Z]{2}\z/
    # Si el formato es válido hay match
    is_valid = patent.match(old_patent_regex) || patent.match(new_patent_regex)

    is_valid ? true : errors.add(:patent, :bad_patent_type)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.where(is_deleted: false)
    if Current.user&.role? == "admin" || Current.user&.role? == "supervisor"
      # Se muestran los autos que no están borrados
      @cars.order(vehicle_number: :asc)
    else 
      # Se muestran los autos que están visibles
      @cars = @cars.where(is_visible: true).where(is_rented: false)
    end
  end

  def new
    # Para la acción view utilizo una variable de instancia vacia
    # Esta variable de instancia vacia se va a rellenar con el formulario correspondiente
    @car = Car.new
  end
  
  def create
    # Se filtran los parámetros instanciando de nuevo
    @car = Car.new(car_params)

    if @car.save
      # Si el auto se guarda correctamente
      # Y se redirige a la página principal
      #!! REDIRECCION A PAGINA PRINCIPAL
      redirect_to cars_path, notice: t('.created')
    else
      # Sino se renderiza de nuevo el formulario new
      # Se pasa como status unprocessable_entity para que TURBO entienda que el formulario no es correcto y se vuelva a renderizar (convención de turbo)
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    car
  end

  def update
    car
    if car.update(car_params)
      redirect_to cars_path, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    car
  end

  def visible
    car
    if (car.toggle(:is_visible).save)
      redirect_to cars_path, notice: t('.visible_toggled')
    else
      redirect_to cars_path, alert: t('.error_visible_toggled')
    end
  end

  def destroy
    car
    car.update_attribute(:is_deleted, true)
    redirect_to cars_path, notice: t('.destroyed')
  end

  private

  def car
    @car ||= Car.find(params[:id])
  end

  def car_params
    # Se quiere que tenga un objeto Car antes que todo el contenido de parámetros
    # Luego se hace el permit con todo lo que debe tener
    params.require(:car).permit(:patent, :model, :vehicle_number, :color, :brand, :photo)
  end
  
end 

app/views/cars/_card.html.erb
<!-- Tarjeta de auto -->
<section class="flex flex-col p-2 pt-4 md:px-4 md:pt-4 mx-4">
  <article class="bg-gray-700 text-gray-200 flex rounded-lg shadow-xl overflow-hidden mb-8 bg-gradient-to-r from-orange-600 to-gray-800 md:flex-nowrap flex-wrap border-2 border-black">
    <%= link_to car_path(car.id), class: "contents" do %>
      <%= image_tag car.photo, alt: "car", class: "relative w-full md:max-w-xs md:max-h-full max-h-48 object-cover border-1 border-black" %>
    <% end %>
    <div class="relative flex flex-col p-4">
      <h1 class="text-3xl mb-2 uppercase font-bold">
        <%= car.brand + " " + car.model + " " + car.color  %>
      </h1>
      <div class="text-justify">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ultrices massa vel mattis varius. Morbi finibus, risus quis tincidunt vestibulum, erat magna hendrerit orci, nec faucibus turpis enim ac arcu. Sed lacinia finibus ante, sed feugiat orci vestibulum id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras porta, libero et maximus dignissim, tortor arcu dictum libero, vel consequat diam ipsum a nisi. Donec facilisis scelerisque nulla, at elementum justo porttitor vel. Nunc sit amet fringilla nisl. Aenean fermentum, mauris ac blandit commodo, libero libero vehicula neque, vel finibus orci magna eget ligula. 
        </p>
      </div>
      <ul class="flex flex-row flex-wrap justify-center md:justify-start mt-8">
        <li><%= link_to t('.view_details'), car_path(car.id), class: "mx-1 text-orange-300 font-bold bg-orange-900 py-2 px-2 rounded hover:brightness-110 border-2 border-black focus:border-orange-900 focus:outline-none focus:ring-orange-900 cursor-pointer" %></li>
      </ul>
    </div>
  </article>
</section>

app/views/cars/_form.html.erb
<div class="mt-10 sm:mt-0">
  <div class="md:grid md:grid-cols-2 md:gap-6">
    <div class="mt-5 md:col-span-2 md:mt-0">
      <%= form_with(model: @car) do |form| %>
        <div class="overflow-hidden shadow sm:rounded-md">
          <div class="bg-white px-4 py-5 sm:p-6">
            <div class="grid grid-cols-6 gap-6">

              <%# Input para brand %>
              <div class="col-span-6 sm:col-span-3">
                <%= form.label :brand, class: "block text-sm font-medium text-gray-700" %>
                <%= form.text_field :brand, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-orange-500 focus:ring-orange-500 sm:text-sm" %>
                <% if @car.errors.full_messages_for(:brand).each  do |error| %>
                    <ul class="list-disc list-inside">
                      <li class="text-xs text-red-500">
                        <%= error %>
                      </li>
                    </ul>
                  <% end %>
                <% end %>
              </div>

              <%# Input para color %>
              <div class="col-span-6 sm:col-span-3">
                <%= form.label :color, class: "block text-sm font-medium text-gray-700" %>
                <%= form.text_field :color, class: "mt-1 rounded-md border-gray-300 shadow-sm focus:border-orange-500 focus:ring-orange-500 sm:text-sm" %>
                <% if @car.errors.full_messages_for(:color).each  do |error| %>
                    <ul class="list-disc list-inside">
                      <li class="text-xs text-red-500">
                        <%= error %>
                      </li>
                    </ul>
                  <% end %>
                <% end %>
              </div>

              <%# Input para patent %>
              <div class="col-span-6 sm:col-span-3">
                <%= form.label :patent, class: "block text-sm font-medium text-gray-700" %>
                <%= form.text_field :patent, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-orange-500 focus:ring-orange-500 sm:text-sm" %>
                <% if @car.errors.full_messages_for(:patent).each  do |error| %>
                    <ul class="list-disc list-inside">
                      <li class="text-xs text-red-500">
                        <%= error %>
                      </li>
                    </ul>
                  <% end %>
                <% end %>
              </div>

              <%# Input para vehicle_number %>
              <div class="col-span-6 sm:col-span-3">
                <%= form.label :vehicle_number, class: "block text-sm font-medium text-gray-700" %>
                <%= form.number_field :vehicle_number, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-orange-500 focus:ring-orange-500 sm:text-sm" %>
                <% if @car.errors.full_messages_for(:vehicle_number).each  do |error| %>
                    <ul class="list-disc list-inside">
                      <li class="text-xs text-red-500">
                        <%= error %>
                      </li>
                    </ul>
                  <% end %>
                <% end %>
              </div>

              <%# Input para password %>
              <div class="col-span-6 sm:col-span-3">
                <%= form.label :model, class: "block text-sm font-medium text-gray-700" %>
                <%= form.text_field :model, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-orange-500 focus:ring-orange-500 sm:text-sm" %>
                <% if @car.errors.full_messages_for(:model).each  do |error| %>
                    <ul class="list-disc list-inside">
                      <li class="text-xs text-red-500">
                        <%= error %>
                      </li>
                    </ul>
                  <% end %>
                <% end %>
              </div>
              
              <%# Input para photo %>
              <div class="col-span-6 sm:col-span-3">
                <%= form.label :photo, class: "block text-sm font-medium text-gray-700" %>
                <%= form.file_field :photo, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-orange-500 focus:ring-orange-500 sm:text-sm" %>
                <% if @car.errors.full_messages_for(:photo).each  do |error| %>
                    <ul class="list-disc list-inside">
                      <li class="text-xs text-red-500">
                        <%= error %>
                      </li>
                    </ul>
                  <% end %>
                <% end %>
              </div>

            </div>
          </div>
          <div class="bg-gray-50 px-4 py-3 text-right sm:px-6">
            <%# Botón de submit %>
          <%= button_tag(type: "submit", 
            class: "inline-flex w-full justify-center rounded-md border border-transparent bg-orange-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-orange-500 focus:ring-offset-2") do %>
            <%= content_tag(:strong, t('.submit')) %>
          <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/_table.html.erb
<section class="m-8">
  <%# Se puede agregar algun elemento por aqui %>
  <article class="overflow-auto rounded-lg shadow hidden md:block select-none">
    <table class="w-full">
      <thead class="text-xs uppercase bg-gray-800 text-gray-200">
        <tr class="border-2 border-black">
          <th class="w-16 p-3 text-sm font-bold tracking-wide text-left whitespace-nowrap"></th>
          <th class="w-20 p-3 text-sm font-bold tracking-wide text-left whitespace-nowrap"><%= t('.state') %></th>
          <th class="w-20 p-3 text-sm font-bold tracking-wide text-left whitespace-nowrap"><%= t('.is_rented') %></th>
          <th class="w-20 p-3 text-sm font-bold tracking-wide text-left whitespace-nowrap"><%= t('.brand') %></th>
          <th class="w-20 p-3 text-sm font-bold tracking-wide text-left whitespace-nowrap"><%= t('.model') %></th>
          <th class="w-20 p-3 text-sm font-bold tracking-wide text-left whitespace-nowrap"><%= t('.patent') %></th>
          <th class="w-20 p-3 text-sm font-bold tracking-wide text-left whitespace-nowrap"><%= t('.vehicle_number') %></th>
          <th class="w-20 p-3 text-sm font-bold tracking-wide text-left whitespace-nowrap"><%= t('.actions') %></th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-100">  
        <% if cars.count > 0 %>
          <%# En caso de haber autos %>
          <% cars.each do |car| %>
            <tr class="<%= class_names('hover:bg-gray-400', {'bg-red-200': !car.is_visible}) %>">
              <td class="p-3 text-sm">
                <%= image_tag car.photo, alt: "car", class: "w-10 h-10 object-cover border border-black max-w-none" %>
              </td>
              <td class="p-3 text-sm text-gray-700 whitespace-nowrap uppercase">
                <span class="<%= class_names('p-1.5 text-xs font-medium uppercase tracking-wider text-gray-200 rounded-lg bg-green-400 border-2 border-black', {'bg-red-500': !car.is_visible}) %>"><%= car.is_visible ? t('.visible') : t('.non_visible') %></span>
              </td>
              <td class="p-3 text-sm text-gray-700 whitespace-nowrap uppercase">
                <span class="<%= class_names('p-1.5 text-xs font-medium uppercase tracking-wider text-gray-200 rounded-lg bg-green-400 border-2 border-black', {'bg-red-500': car.is_rented}) %>"><%= car.is_rented ? t('.is_rented') : t('.not_rented') %></span>
              </td>
              <td class="p-3 text-sm text-gray-700 whitespace-nowrap uppercase"><%= car.brand %></td>
              <td class="p-3 text-sm text-gray-700 whitespace-nowrap uppercase"><%= car.model %></td>
              <td class="p-3 text-sm text-gray-700 whitespace-nowrap uppercase"><%= car.patent %></td>
              <td class="p-3 text-sm text-gray-700 whitespace-nowrap uppercase"><%= car.vehicle_number %></td>
              <td class="p-3 text-gray-700 whitespace-nowrap uppercase">
                <%= link_to t('.view_details'), car_path(car.id), class: "p-1.5 focus:outline-none text-white bg-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:ring-yellow-300 font-medium rounded-lg text-sm dark:focus:ring-yellow-900 border border-black" %>
                <%= link_to t('.edit'), edit_car_path(car), class: "p-1.5 focus:outline-none text-white bg-blue-400 hover:bg-blue-500 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm dark:focus:ring-blue-900 border border-black" if Current.user&.role? == "admin" %>
                <%= button_to t('.visibility'), visible_car_path(car.id), method: :put, form_class: "contents", class: "inline p-1 focus:outline-none text-white bg-violet-400 hover:bg-violet-500 focus:ring-4 focus:ring-violet-300 font-medium rounded-lg text-sm dark:focus:ring-violet-900 border border-black uppercase" if Current.user&.role? == "admin" %>
                <%= link_to "Ver Historial", cars_usage_history_path(car.id), class: "p-1.5 focus:outline-none text-white bg-pink-400 hover:bg-pink-500 focus:ring-4 focus:ring-pink-300 font-medium rounded-lg text-sm dark:focus:ring-pink-900 border border-black" %>
                <%= link_to t('.delete'), car_path(car.id), data: {
                                  turbo_method: :delete,
                                  turbo_confirm: t('common.confirm')
                                  }, class: "p-1.5 focus:outline-none text-white bg-red-400 hover:bg-red-500 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm dark:focus:ring-red-900 border border-black" if Current.user&.role? == "admin" %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <%# En caso de no haber autos %>
          <tr>
            <td class="p-3 text-sm text-gray-700 whitespace-nowrap uppercase"> <%= t('.no_records_available') %> </td>
          </tr>
        <% end %>
      </tbody>  
    </table>
  </article>
  
  <%# Para la vista mobile %>
  <article class="grid grid-cols-1 sm:grid-cols-2 gap-4 md:hidden">
    <% if cars.count > 0 %>
      <%# En caso de haber autos %>
      <% cars.each do |car| %>
        <div class="space-y-3 p-4 rounded-lg shadow border-2 border-black bg-gray-800">
          <div class="flex items-center space-x-2 text-sm flex-wrap gap-2">
              <div>
                <%= image_tag car.photo, alt: "car", class: "w-10 h-10 object-cover border border-black max-w-none" %>
              </div>
              <div>
                <span class="<%= class_names('p-1.5 text-xs font-medium uppercase tracking-wider text-gray-200 rounded-lg bg-green-400 border-2 border-black whitespace-nowrap', {'bg-red-500': !car.is_visible}) %>"><%= car.is_visible ? t('.visible') : t('.non_visible') %></span>
                </span>
              </div>
          </div>
          <div class="text-sm text-gray-200 flex flex-col">
            <p>
              <span class="text-sm text-gray-200 uppercase font-bold"><%= t('.brand') %>:</span>
              <span class="text-sm text-gray-200 uppercase"><%= car.brand %></span>
            </p>
            <p>
              <span class="text-sm text-gray-200 uppercase font-bold"><%= t('.model') %>:</span>
              <span class="text-sm text-gray-200 uppercase"><%= car.model %></span>
            </p>
            <p>
              <span class="text-sm text-gray-200 uppercase font-bold"><%= t('.patent') %>:</span>
              <span class="text-sm text-gray-200 uppercase"><%= car.patent %></span>
            </p>
            <p>
              <span class="text-sm text-gray-200 uppercase font-bold"><%= t('.vehicle_number') %>:</span>
              <span class="text-sm text-gray-200 uppercase"><%= car.vehicle_number %></span>
            </p>
          </div>
          <div class="flex flex-wrap gap-2 uppercase">
            <%= link_to "Ver detalle", car_path(car.id), class: "p-1.5 focus:outline-none text-white bg-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:ring-yellow-300 font-medium rounded-lg text-sm dark:focus:ring-yellow-900 border border-black" %>
            <%= link_to "Editar", edit_car_path(car), class: "p-1.5 focus:outline-none text-white bg-blue-400 hover:bg-blue-500 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm dark:focus:ring-blue-900 border border-black" if Current.user&.role? == "admin" %>
            <%= button_to "Visibilidad", visible_car_path(car.id), method: :put, form_class: "contents", class: "inline p-1 focus:outline-none text-white bg-violet-400 hover:bg-violet-500 focus:ring-4 focus:ring-violet-300 font-medium rounded-lg text-sm dark:focus:ring-violet-900 border border-black uppercase" if Current.user&.role? == "admin" %>
            <%= link_to "Ver Historial", cars_usage_history_path(car.id), class: "p-1.5 focus:outline-none text-white bg-pink-400 hover:bg-pink-500 focus:ring-4 focus:ring-pink-300 font-medium rounded-lg text-sm dark:focus:ring-pink-900 border border-black" %>
            <%= link_to "Eliminar", car_path(car.id), data: {
                              turbo_method: :delete,
                              turbo_confirm: t('common.confirm')
                              }, class: "p-1.5 focus:outline-none text-white bg-red-400 hover:bg-red-500 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm dark:focus:ring-red-900 border border-black" if Current.user&.role? == "admin" %>
          </div>
        </div>
      <% end %>
    <% else %>
      <%# En caso de no haber autos %>
      <h4 class="p-3 text-sm text-gray-700 whitespace-nowrap uppercase"> <%= t('.no_records_available') %></h4>
    <% end %>
  </article>
</section>

app/views/cars/edit.html.erb
<%= render 'form' %>

app/views/cars/index.html.erb
<section class="mx-4 mb-2 p-4 bg-gray-800 text-gray-200 rounded-b-lg border-2 border-black">
  <h4 class="text-2xl uppercase text-center">
    <%= t('.title') %>
  </h4>
</section>

<% if Current.user&.role? == "admin" || Current.user&.role? == "supervisor" %>
  <%# Renderizo tabla %>
  <%= render "table", cars: @cars %>
<% else %>
  <%# Renderizar solo autos disponible al cliente %>
  <% if(@cars.count > 0)%>
        <% @cars.each do |car| %>
          <%= render "card", car: car %>
        <% end %>
  <% else %>
    <section class="mx-4 mb-2 p-4">
      <h4> <%= t('.no_records_available') %> </h4>
    </section>
  <% end %>
<% end %>

app/views/cars/new.html.erb
<%= render 'form' %>

app/views/cars/show.html.erb
<!-- Título detalles de auto -->
<section class="mx-4 mb-2 p-4 bg-gray-800 text-gray-200 rounded-b-lg border-2 border-black">
  <h4 class="text-2xl uppercase text-center">
    <%= t('.title') %>
  </h4>
</section>

<!-- Detalles de auto -->
<section class="flex flex-col p-2 pt-4 md:px-4 md:pt-4 mx-4">
  <article class="bg-gray-700 text-gray-200 flex rounded-lg shadow-xl overflow-hidden mb-8 bg-gradient-to-r from-orange-800 to-orange-400 md:flex-nowrap flex-wrap border-2 border-black">
    <%= image_tag @car.photo, alt: "car", class: "relative w-full md:max-w-xs md:max-h-full max-h-48 object-cover border-1 border-black" %>
    <div class="flex flex-col w-full justify-center">
      <ul class="flex flex-col gap-2 px-2 my-2">
        <li class="bg-gray-700 px-4 py-3 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 rounded-lg border-2 border-black">
          <dt class="text-sm font-medium text-orange-300"><%= t('.brand') %></dt>
          <dd class="mt-1 text-sm text-gray-200 sm:col-span-2 sm:mt-0"><%= @car.brand.upcase %></dd>
        </li>
        <li class="bg-gray-700 px-4 py-3 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 rounded-lg border-2 border-black">
          <dt class="text-sm font-medium text-orange-300"><%= t('.model') %></dt>
          <dd class="mt-1 text-sm text-gray-200 sm:col-span-2 sm:mt-0"><%= @car.model.upcase %></dd>
        </li>
        <% if Current.user&.role? == "admin" || Current.user&.role? == "supervisor" %>
          <li class="bg-gray-700 px-4 py-3 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 rounded-lg border-2 border-black">
            <dt class="text-sm font-medium text-orange-300"><%= t('.patent') %></dt>
            <dd class="mt-1 text-sm text-gray-200 sm:col-span-2 sm:mt-0"><%= @car.patent.upcase %></dd>
          </li>
          <li class="bg-gray-700 px-4 py-3 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 rounded-lg border-2 border-black">
            <dt class="text-sm font-medium text-orange-300"><%= t('.vehicle_number') %></dt>
            <dd class="mt-1 text-sm text-gray-200 sm:col-span-2 sm:mt-0"><%= @car.vehicle_number %></dd>
          </li>
        <% end %>
        <li class="bg-gray-700 px-4 py-3 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 rounded-lg border-2 border-black">
          <dt class="text-sm font-medium text-orange-300"><%= t('.color') %></dt>
          <dd class="mt-1 text-sm text-gray-200 sm:col-span-2 sm:mt-0"><%= @car.color.upcase %></dd>
        </li>
      </ul>
    </div>
  </article>
  <div class="flex justify-center text-center font-bold text-5xl stroke-black">
    <%=link_to t('.rent'), new_rental_path(@car.id),class: "mt-2 mx-2 text-white font-bold p-4 bg-orange-600 rounded-lg w-96 hover:brightness-150 border-2 border-black" if Current.user&.role? == 'client' && !Current.user.rentals.find_by(is_active:true) %>
  </div>
</section>
  